name:        tinderbox
version:     0.0.1
license:     BSD3
author:      John Wiegley
maintainer:  johnw@newartisans.com
description: Implementation of expression language used by the Tinderbox application

ghc-options:
   - -Wall
   - -Wno-missing-home-modules

dependencies:
  - aeson
  - base >= 4.5
  - bytestring
  - cassava
  - comonad
  - constraints
  - containers
  - data-default
  - free
  - hashable
  - lens
  - megaparsec
  - mtl
  - pretty
  - pretty-show
  - profunctors
  - row-types
  - semigroupoids
  - simple-amount >= 0.2.0
  - split
  - text
  - time
  - transformers
  - unordered-containers
  - vector

library:
  source-dirs: src
  exposed-modules:
    - Tinderbox.Expr
    - Tinderbox.Eval
    - Tinderbox.Parser
    - Tinderbox.Types

tests:
  tinderbox-tests:
    main: Main.hs
    source-dirs: tests
    dependencies:
      - HUnit
      - hedgehog
      - here
      - tasty
      - tasty-hedgehog
      - tasty-hunit
      - tinderbox

executables:
  tinderbox:
    main: Main.hs
    source-dirs: bin
    other-modules:
      - Options
    dependencies:
      - tinderbox
      - optparse-applicative
